Maj prochains events
tadx-group/tadx-group.github.io pull request #47
Opened 2020-09-27 13:16 UTC by philippart-s

Maj compteur page d'accueil et liste des evts jusqu'à Noël

2020-09-28 07:11 UTC, klaukf requested changes

2020-09-28 07:11 UTC, klaukf commented on agenda.html
> +      <p>Atelier sketch noting</p>
```suggestion
      <p>Atelier sketchnoting</p>    
```

2020-10-01 11:57 UTC, philippart-s commented
@klaukf tu n'as peut être pas vu mais suite à ta demande de changement il faut que tu revalide la PR 😉

2020-10-01 12:07 UTC, klaukf approved these changes

2020-10-01 12:07 UTC, merged

2020-10-01 12:08 UTC, philippart-s commented
merci 💘